services:
  app:
    build: .
    ports:
      - "8080:8080"
    command: ["./main"]
    depends_on:
      - postgresdb
  postgresdb:
    image: postgres:latest
    container_name: postgresdb
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: web-monitor-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/postgres